# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fce81e1d55b5352002dd6332a6a8e3963ce282d888ea3e0b084021f6d1b1c75324a42b9381fc849c2145f4b36df0d73f15d8e9d0ec59fd2a1f1c22f2e78815c0

test:
  secret_key_base: 2ea80e2d9c6dbd0726153465d99b9e89edc3486cdfce36b5a17416d0d31c68a0d8ac539f095436d6a15d329a25198db8cacbaae4aa1499de22ce59a4063d29b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
